# see https://github.com/marketplace/actions/release-drafter
# For RESOLVED_VERSION
# Use for initial alpha version
# version-template: '$MAJOR.$MINOR.$PATCH-alpha'
version-template: '$MAJOR.$MINOR.$PATCH'
#
name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
#
template: |
  ### ProfessionSnooper $RESOLVED_VERSION
  [Release Notes](https://github.com/msurkein/$REPOSITORY/releases/tag/$RESOLVED_VERSION) | [Full Changelog](https://github.com/msurkein/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION) | [Release Page](https://github.com/msurkein/$REPOSITORY/releases)
  
  #### What’s Changed

  $CHANGES
  
  ### Contributors:
  $CONTRIBUTORS
  
  #### Links:

  - [Curse Forge](https://www.curseforge.com/wow/addons/professionsnooper/files) | [Curse Forge Legacy](https://legacy.curseforge.com/wow/addons/professionsnooper/files)
